# Generated by Django 4.1 on 2024-12-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0005_alter_movie_actors_alter_movie_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="tickets_available",
            field=models.IntegerField(default=0),
        ),
    ]
