# Generated by Django 4.1 on 2024-12-09 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0006_actor_tickets_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="cinema.actor",
            ),
        ),
    ]
