# Generated by Django 4.1 on 2024-12-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0007_ticket_actor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="actor",
        ),
    ]
