# Generated by Django 4.1 on 2024-12-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0008_remove_ticket_actor"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviesession",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
