# Generated by Django 4.1 on 2024-12-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0009_moviesession_is_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actor",
            name="tickets_available",
        ),
        migrations.RemoveField(
            model_name="moviesession",
            name="is_available",
        ),
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(to="cinema.actor"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(to="cinema.genre"),
        ),
    ]
